[tool.poetry]
name = "faag"
version = "0.1.0"
description = ""
authors = ["Vetrichelvan <pythonhub.py@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
black = {extras = ["d"], version = "^22.8.0"}
pylint = "^2.15.3"
pylint-quotes = "^0.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
