name: "Delete workflow runs"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  delete:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '0.0.') && !contains(github.event.head_commit.message, 'build:')
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.3
        with:
          token: ${{ secrets.GH_TOKEN }}
          keep_minimum_runs: 3
          retain_days: 1


