name: "Delete workflow runs"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  delete:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.3
        with:
          token: ${{ secrets.GH_TOKEN }}
          keep_minimum_runs: 3
          retain_days: 1


